version: '3.3'

services:
  app1:
    image: traefik/whoami
    environment:
      WHOAMI_NAME: app1
    ports:
      - "5001:80"
  app2:
    image: traefik/whoami
    environment:
      WHOAMI_NAME: app2
    ports:
      - "5002:80"
  app3:
    image: traefik/whoami
    environment:
      WHOAMI_NAME: app3
    ports:
      - "5003:80"
  lb:
    image: nginx
    depends_on: 
      - app1
      - app2
      - app3
    ports:
      - "80:80"
    volumes:
      - default.conf:/etc/nginx/conf.d/
volumes: 
  default.conf: